---
sudo: required
dist: trusty
language: node_js

node_js:
  - 9
python:
  - 3.6.x

addons:
  apt:
    packages:
      - imagemagick
      - graphicsmagic

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  - npm install
  - npm install --global gulp-cli

script:
  - gulp build

after_success:
  - zip -q site.zip -r public/
  - ls -l site.zip



