---
dist: bionic
language: node_js

node_js:
  - 9

git:
  depth: false

addons:
  apt:
    packages:
      - imagemagick
      - graphicsmagick

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
  - npm install --global gulp-cli

script:
  - gulp build
  - if [[ "$TRAVIS_TAG" != "" ]]; then mv ./public site_$TRAVIS_TAG; fi
  - if [[ "$TRAVIS_TAG" != "" ]]; then zip site_$TRAVIS_TAG.zip -r site_$TRAVIS_TAG; fi

# "travis lint" complaints about skip_cleanup; looking at
# https://docs.travis-ci.com/user/deployment-v2#cleaning-up-the-git-working-directory
# I see that the deploy v2 approach is to skip by default, but that v1 is still
# default, so we're leaving that option in. -- 2020-02
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file: ./site_$TRAVIS_TAG.zip
    on:
      tags: true
